services:
  web:
    build:
      context: ./
      target: runner
    image: example-image
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    platform: linux/amd64