services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api-hublocal
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
        - hublocal

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    networks:
      - hublocal
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
    hublocal:
        driver: bridge

volumes:
    db:
        driver: local
